server.port: 80

# 定位模板的目录
spring.mvc.view.prefix: classpath:/templates/
# 给返回的页面添加后缀名
spring.mvc.view.suffix: .html

spring.datasource:
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/test?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
  username: root
  password: 123456
  type: com.alibaba.druid.pool.DruidDataSource
  initialSize: 5
  minIdle: 5
  maxActive: 20
  maxWait: 60000
  timeBetweenEvictionRunsMillis: 60000
  minEvictableIdleTimeMillis: 300000
  validationQuery: SELECT 1 FROM DUAL
  testWhileIdle: true
  testOnBorrow: false
  testOnReturn: false
  poolPreparedStatements: true
# 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
  filters: stat,wall,log4j
  maxPoolPreparedStatementPerConnectionSize: 20
  useGlobalDataSourceStat: true
  connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    


  #公共配置与profiles选择无关
mybatis:
  configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #typeAliasesPackage: com.aspire.cmop.model
  mapperLocations: classpath:mapper/*Mapper.xml,classpath*:sqlmap/*Mapper.xml