server.port: 80

spring.datasource:
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/test?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
  username: root
  password: 123456

  #公共配置与profiles选择无关
mybatis:
  configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #typeAliasesPackage: com.aspire.cmop.model
  mapperLocations: classpath:mapper/*Mapper.xml,classpath*:sqlmap/*Mapper.xml